/**
 * Type declarations for the TeaVM-compiled Operaton DMN engine bundle.
 * The bundle is generated by `engine-dmn-teavm/` and copied here by `make build-operaton-dmn`.
 */
declare module "./operaton-dmn-bundle.js" {
    /**
     * TeaVM entry-point starter. Call with empty args to initialise the engine.
     * On success, `globalThis.OperatonDmnEngine.evaluateDecision` is installed.
     */
    export function main(args: string[], callback: (err?: Error) => void): void;
}
